sudo: required

language: generic

git:
  depth: false

dist:
  xenial

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - docker pull moussavdb/build-java-native

script:
  - chmod +x deploy-maven-central.sh
  - docker run -v $PWD:/src -v $HOME/.m2:/root/.m2 -e VAULT_TOKEN=$VAULT_TOKEN -e BRANCH=$TRAVIS_BRANCH moussavdb/build-java-native ./deploy-maven-central.sh
